<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class PokedexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pokedexes')->insert([
			[
				'id' => 1,
				'name' => 'Bulbasaur',
				'type1' => 'Grass',
				'type2' => 'Poison',
				'HP' => 45,
				'attack' => 49,
				'defence' => 49,
				'sp_attack' => 65, 
				'sp_defence' => 65,
				'speed' => 45,
				'generation' => 1,
				'legendary' => 0,
			],
			[
        		'id' => 2,
        	    'name' => 'Ivysaur',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 62,
    	        'defence' => 63,
	            'sp_attack' => 80, 
            	'sp_defence' => 80,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 3,
        	    'name' => 'Venusaur',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 80,
        	    'attack' => 82,
    	        'defence' => 83,
	            'sp_attack' => 100, 
            	'sp_defence' => 100,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 4,
        	    'name' => 'Charmander',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 39,
        	    'attack' => 52,
    	        'defence' => 43,
	            'sp_attack' => 60, 
            	'sp_defence' => 50,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 5,
        	    'name' => 'Charmeleon',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 58,
        	    'attack' => 64,
    	        'defence' => 58,
	            'sp_attack' => 80, 
            	'sp_defence' => 65,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 6,
        	    'name' => 'Charizard',
    	        'type1' => 'Fire',
	            'type2' => 'Flying',
            	'HP' => 78,
        	    'attack' => 84,
    	        'defence' => 78,
	            'sp_attack' => 109, 
            	'sp_defence' => 85,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 7,
        	    'name' => 'Squirtle',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 44,
        	    'attack' => 48,
    	        'defence' => 65,
	            'sp_attack' => 50, 
            	'sp_defence' => 64,
        	    'speed' => 43,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 8,
        	    'name' => 'Wartortle',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 59,
        	    'attack' => 63,
    	        'defence' => 80,
	            'sp_attack' => 65, 
            	'sp_defence' => 80,
        	    'speed' => 58,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 9,
        	    'name' => 'Blastoise',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 79,
        	    'attack' => 83,
    	        'defence' => 100,
	            'sp_attack' => 85, 
            	'sp_defence' => 105,
        	    'speed' => 78,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 10,
        	    'name' => 'Caterpie',
    	        'type1' => 'Bug',
	            'type2' => '',
            	'HP' => 45,
        	    'attack' => 30,
    	        'defence' => 35,
	            'sp_attack' => 20, 
            	'sp_defence' => 20,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 11,
        	    'name' => 'Metapod',
    	        'type1' => 'Bug',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 20,
    	        'defence' => 55,
	            'sp_attack' => 25, 
            	'sp_defence' => 25,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 12,
        	    'name' => 'Butterfree',
    	        'type1' => 'Bug',
	            'type2' => 'Flying',
            	'HP' => 60,
        	    'attack' => 45,
    	        'defence' => 50,
	            'sp_attack' => 90, 
            	'sp_defence' => 80,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 13,
        	    'name' => 'Weedle',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 40,
        	    'attack' => 35,
    	        'defence' => 30,
	            'sp_attack' => 20, 
            	'sp_defence' => 20,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 14,
        	    'name' => 'Kakuna',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 25,
    	        'defence' => 50,
	            'sp_attack' => 25, 
            	'sp_defence' => 25,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 15,
        	    'name' => 'Beedrill',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 65,
        	    'attack' => 90,
    	        'defence' => 40,
	            'sp_attack' => 45, 
            	'sp_defence' => 80,
        	    'speed' => 75,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 16,
        	    'name' => 'Pidgey',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 45,
    	        'defence' => 40,
	            'sp_attack' => 35, 
            	'sp_defence' => 35,
        	    'speed' => 56,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 17,
        	    'name' => 'Pidgeotto',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 63,
        	    'attack' => 60,
    	        'defence' => 55,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 71,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 18,
        	    'name' => 'Pidgeot',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 83,
        	    'attack' => 80,
    	        'defence' => 75,
	            'sp_attack' => 70, 
            	'sp_defence' => 70,
        	    'speed' => 101,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 19,
        	    'name' => 'Rattata',
    	        'type1' => 'Normal',
	            'type2' => '',
            	'HP' => 30,
        	    'attack' => 56,
    	        'defence' => 35,
	            'sp_attack' => 25, 
            	'sp_defence' => 35,
        	    'speed' => 72,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 20,
        	    'name' => 'Raticate',
    	        'type1' => 'Normal',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 81,
    	        'defence' => 60,
	            'sp_attack' => 50, 
            	'sp_defence' => 70,
        	    'speed' => 97,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 21,
        	    'name' => 'Spearow',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 60,
    	        'defence' => 30,
	            'sp_attack' => 31, 
            	'sp_defence' => 31,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 22,
        	    'name' => 'Fearow',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 65,
        	    'attack' => 90,
    	        'defence' => 65,
	            'sp_attack' => 61, 
            	'sp_defence' => 61,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 23,
        	    'name' => 'Ekans',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 35,
        	    'attack' => 60,
    	        'defence' => 44,
	            'sp_attack' => 40, 
            	'sp_defence' => 54,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 24,
        	    'name' => 'Arbok',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 60,
        	    'attack' => 85,
    	        'defence' => 69,
	            'sp_attack' => 65, 
            	'sp_defence' => 79,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 25,
        	    'name' => 'Pikachu',
    	        'type1' => 'Electric',
	            'type2' => '',
            	'HP' => 35,
        	    'attack' => 55,
    	        'defence' => 40,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 26,
        	    'name' => 'Raichu',
    	        'type1' => 'Electric',
	            'type2' => '',
            	'HP' => 60,
        	    'attack' => 90,
    	        'defence' => 55,
	            'sp_attack' => 90, 
            	'sp_defence' => 80,
        	    'speed' => 110,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 27,
        	    'name' => 'Sandshrew',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 75,
    	        'defence' => 85,
	            'sp_attack' => 20, 
            	'sp_defence' => 30,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 28,
        	    'name' => 'Sandslash',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 75,
        	    'attack' => 100,
    	        'defence' => 110,
	            'sp_attack' => 45, 
            	'sp_defence' => 55,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 29,
        	    'name' => 'Nidoran(Female)',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 47,
    	        'defence' => 52,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 41,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 30,
        	    'name' => 'Nidorina',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 70,
        	    'attack' => 62,
    	        'defence' => 67,
	            'sp_attack' => 55, 
            	'sp_defence' => 55,
        	    'speed' => 56,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 31,
        	    'name' => 'Nidoqueen',
    	        'type1' => 'Poison',
	            'type2' => 'Ground',
            	'HP' => 90,
        	    'attack' => 92,
    	        'defence' => 87,
	            'sp_attack' => 75, 
            	'sp_defence' => 85,
        	    'speed' => 76,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 32,
        	    'name' => 'Nidoran(Male)',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 46,
        	    'attack' => 57,
    	        'defence' => 40,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 33,
        	    'name' => 'Nidorino',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 61,
        	    'attack' => 72,
    	        'defence' => 57,
	            'sp_attack' => 55, 
            	'sp_defence' => 55,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 34,
        	    'name' => 'Nidoking',
    	        'type1' => 'Poison',
	            'type2' => 'Ground',
            	'HP' => 81,
        	    'attack' => 102,
    	        'defence' => 77,
	            'sp_attack' => 85, 
            	'sp_defence' => 75,
        	    'speed' => 85,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 35,
        	    'name' => 'Clefairy',
    	        'type1' => 'Fairy',
	            'type2' => '',
            	'HP' => 70,
        	    'attack' => 45,
    	        'defence' => 48,
	            'sp_attack' => 60, 
            	'sp_defence' => 65,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 36,
        	    'name' => 'Clefable',
    	        'type1' => 'Fairy',
	            'type2' => '',
            	'HP' => 95,
        	    'attack' => 70,
    	        'defence' => 73,
	            'sp_attack' => 95, 
            	'sp_defence' => 90,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 37,
        	    'name' => 'Vulpix',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 38,
        	    'attack' => 41,
    	        'defence' => 40,
	            'sp_attack' => 50, 
            	'sp_defence' => 65,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 38,
        	    'name' => 'Ninetales',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 73,
        	    'attack' => 76,
    	        'defence' => 75,
	            'sp_attack' => 81, 
            	'sp_defence' => 100,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 39,
        	    'name' => 'Jigglypuff',
    	        'type1' => 'Normal',
	            'type2' => 'Fairy',
            	'HP' => 115,
        	    'attack' => 45,
    	        'defence' => 20,
	            'sp_attack' => 45, 
            	'sp_defence' => 25,
        	    'speed' => 20,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 40,
        	    'name' => 'Wigglytuff',
    	        'type1' => 'Normal',
	            'type2' => 'Fairy',
            	'HP' => 140,
        	    'attack' => 70,
    	        'defence' => 45,
	            'sp_attack' => 85, 
            	'sp_defence' => 50,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 41,
        	    'name' => 'Zubat',
    	        'type1' => 'Poison',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 45,
    	        'defence' => 35,
	            'sp_attack' => 30, 
            	'sp_defence' => 40,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 42,
        	    'name' => 'Golbat',
    	        'type1' => 'Poison',
	            'type2' => 'Flying',
            	'HP' => 75,
        	    'attack' => 80,
    	        'defence' => 70,
	            'sp_attack' => 65, 
            	'sp_defence' => 75,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 43,
        	    'name' => 'Oddish',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 50,
    	        'defence' => 55,
	            'sp_attack' => 75, 
            	'sp_defence' => 65,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 44,
        	    'name' => 'Gloom',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 65,
    	        'defence' => 70,
	            'sp_attack' => 85, 
            	'sp_defence' => 75,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 45,
        	    'name' => 'Vileplume',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 75,
        	    'attack' => 80,
    	        'defence' => 85,
	            'sp_attack' => 110, 
            	'sp_defence' => 90,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 46,
        	    'name' => 'Paras',
    	        'type1' => 'Bug',
	            'type2' => 'Grass',
            	'HP' => 35,
        	    'attack' => 70,
    	        'defence' => 55,
	            'sp_attack' => 45, 
            	'sp_defence' => 55,
        	    'speed' => 25,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 47,
        	    'name' => 'Parasect',
    	        'type1' => 'Bug',
	            'type2' => 'Grass',
            	'HP' => 60,
        	    'attack' => 95,
    	        'defence' => 80,
	            'sp_attack' => 60, 
            	'sp_defence' => 80,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 48,
        	    'name' => 'Venonat',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 55,
    	        'defence' => 50,
	            'sp_attack' => 40, 
            	'sp_defence' => 55,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 49,
        	    'name' => 'Venomoth',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 70,
        	    'attack' => 65,
    	        'defence' => 60,
	            'sp_attack' => 90, 
            	'sp_defence' => 75,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 50,
        	    'name' => 'Diglett',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 10,
        	    'attack' => 55,
    	        'defence' => 25,
	            'sp_attack' => 35, 
            	'sp_defence' => 45,
        	    'speed' => 95,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 51,
        	    'name' => 'Dugtrio',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 35,
        	    'attack' => 80,
    	        'defence' => 50,
	            'sp_attack' => 50, 
            	'sp_defence' => 70,
        	    'speed' => 120,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 52,
        	    'name' => 'Meowth',
    	        'type1' => 'Normal',
	            'type2' => '',
            	'HP' => 40,
        	    'attack' => 45,
    	        'defence' => 35,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 53,
        	    'name' => 'Persian',
    	        'type1' => 'Normal',
	            'type2' => 'Poison',
            	'HP' => 65,
        	    'attack' => 70,
    	        'defence' => 60,
	            'sp_attack' => 65, 
            	'sp_defence' => 65,
        	    'speed' => 115,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 54,
        	    'name' => 'Psyduck',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 52,
    	        'defence' => 48,
	            'sp_attack' => 65, 
            	'sp_defence' => 50,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 55,
        	    'name' => 'Golduck',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 80,
        	    'attack' => 82,
    	        'defence' => 78,
	            'sp_attack' => 95, 
            	'sp_defence' => 80,
        	    'speed' => 85,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 56,
        	    'name' => 'Mankey',
    	        'type1' => 'Fighting',
	            'type2' => '',
            	'HP' => 40,
        	    'attack' => 80,
    	        'defence' => 35,
	            'sp_attack' => 35, 
            	'sp_defence' => 45,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 57,
        	    'name' => 'Primeape',
    	        'type1' => 'Fighting',
	            'type2' => '',
            	'HP' => 65,
        	    'attack' => 105,
    	        'defence' => 60,
	            'sp_attack' => 60, 
            	'sp_defence' => 70,
        	    'speed' => 95,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 58,
        	    'name' => 'Growlithe',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 70,
    	        'defence' => 45,
	            'sp_attack' => 70, 
            	'sp_defence' => 50,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 59,
        	    'name' => 'Arcanine',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 90,
        	    'attack' => 110,
    	        'defence' => 80,
	            'sp_attack' => 100, 
            	'sp_defence' => 80,
        	    'speed' => 95,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 60,
        	    'name' => 'Poliwag',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 40,
        	    'attack' => 50,
    	        'defence' => 40,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 61,
        	    'name' => 'Poliwhirl',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 65,
        	    'attack' => 65,
    	        'defence' => 65,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 62,
        	    'name' => 'Poliwrath',
    	        'type1' => 'Water',
	            'type2' => 'Fighting',
            	'HP' => 90,
        	    'attack' => 95,
    	        'defence' => 95,
	            'sp_attack' => 70, 
            	'sp_defence' => 90,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 63,
        	    'name' => 'Abra',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 25,
        	    'attack' => 20,
    	        'defence' => 15,
	            'sp_attack' => 105, 
            	'sp_defence' => 55,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 64,
        	    'name' => 'Kadabra',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 40,
        	    'attack' => 35,
    	        'defence' => 30,
	            'sp_attack' => 120, 
            	'sp_defence' => 70,
        	    'speed' => 105,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 65,
        	    'name' => 'Alakazam',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 50,
    	        'defence' => 45,
	            'sp_attack' => 135, 
            	'sp_defence' => 95,
        	    'speed' => 120,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 66,
        	    'name' => 'Machop',
    	        'type1' => 'Fighting',
	            'type2' => '',
            	'HP' => 70,
        	    'attack' => 80,
    	        'defence' => 50,
	            'sp_attack' => 35, 
            	'sp_defence' => 35,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 67,
        	    'name' => 'Machoke',
    	        'type1' => 'Fighting',
	            'type2' => '',
            	'HP' => 80,
        	    'attack' => 100,
    	        'defence' => 70,
	            'sp_attack' => 50, 
            	'sp_defence' => 60,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 68,
        	    'name' => 'Machamp',
    	        'type1' => 'Fighting',
	            'type2' => '',
            	'HP' => 90,
        	    'attack' => 130,
    	        'defence' => 80,
	            'sp_attack' => 65, 
            	'sp_defence' => 85,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 69,
        	    'name' => 'Bellsprout',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 50,
        	    'attack' => 75,
    	        'defence' => 35,
	            'sp_attack' => 70, 
            	'sp_defence' => 30,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 70,
        	    'name' => 'Weepinbell',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 65,
        	    'attack' => 90,
    	        'defence' => 50,
	            'sp_attack' => 85, 
            	'sp_defence' => 45,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 71,
        	    'name' => 'Victreebel',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 80,
        	    'attack' => 105,
    	        'defence' => 65,
	            'sp_attack' => 100, 
            	'sp_defence' => 70,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 72,
        	    'name' => 'Tentacool',
    	        'type1' => 'Water',
	            'type2' => 'Poison',
            	'HP' => 40,
        	    'attack' => 40,
    	        'defence' => 35,
	            'sp_attack' => 50, 
            	'sp_defence' => 100,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 73,
        	    'name' => 'Tentacruel',
    	        'type1' => 'Water',
	            'type2' => 'Poison',
            	'HP' => 80,
        	    'attack' => 70,
    	        'defence' => 65,
	            'sp_attack' => 80, 
            	'sp_defence' => 120,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 74,
        	    'name' => 'Geodude',
    	        'type1' => 'Rock',
	            'type2' => 'Ground',
            	'HP' => 40,
        	    'attack' => 80,
    	        'defence' => 100,
	            'sp_attack' => 30, 
            	'sp_defence' => 30,
        	    'speed' => 20,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 75,
        	    'name' => 'Graveler',
    	        'type1' => 'Rock',
	            'type2' => 'Ground',
            	'HP' => 55,
        	    'attack' => 95,
    	        'defence' => 115,
	            'sp_attack' => 45, 
            	'sp_defence' => 45,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 76,
        	    'name' => 'Golem',
    	        'type1' => 'Rock',
	            'type2' => 'Ground',
            	'HP' => 80,
        	    'attack' => 120,
    	        'defence' => 130,
	            'sp_attack' => 55, 
            	'sp_defence' => 65,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 77,
        	    'name' => 'Ponyta',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 85,
    	        'defence' => 55,
	            'sp_attack' => 65, 
            	'sp_defence' => 65,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 78,
        	    'name' => 'Rapidash',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 65,
        	    'attack' => 100,
    	        'defence' => 70,
	            'sp_attack' => 80, 
            	'sp_defence' => 80,
        	    'speed' => 105,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 79,
        	    'name' => 'Slowpoke',
    	        'type1' => 'Water',
	            'type2' => 'Psychic',
            	'HP' => 90,
        	    'attack' => 65,
    	        'defence' => 65,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 15,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 80,
        	    'name' => 'Slowbro',
    	        'type1' => 'Water',
	            'type2' => 'Psychic',
            	'HP' => 95,
        	    'attack' => 75,
    	        'defence' => 30,
	            'sp_attack' => 120, 
            	'sp_defence' => 70,
        	    'speed' => 105,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 81,
        	    'name' => 'Magnemite',
    	        'type1' => 'Electric',
	            'type2' => 'Steel',
            	'HP' => 25,
        	    'attack' => 35,
    	        'defence' => 70,
	            'sp_attack' => 95, 
            	'sp_defence' => 55,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 82,
        	    'name' => 'Magneton',
    	        'type1' => 'Electric',
	            'type2' => 'Steel',
            	'HP' => 50,
        	    'attack' => 60,
    	        'defence' => 95,
	            'sp_attack' => 120, 
            	'sp_defence' => 70,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 83,
        	    'name' => 'Farfetch\'d',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 52,
        	    'attack' => 65,
    	        'defence' => 50,
	            'sp_attack' => 58, 
            	'sp_defence' => 62,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 84,
        	    'name' => 'Doduo',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 35,
        	    'attack' => 85,
    	        'defence' => 45,
	            'sp_attack' => 35, 
            	'sp_defence' => 35,
        	    'speed' => 75,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 85,
        	    'name' => 'Dodrio',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 60,
        	    'attack' => 110,
    	        'defence' => 70,
	            'sp_attack' => 60, 
            	'sp_defence' => 60,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 86,
        	    'name' => 'Seel',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 65,
        	    'attack' => 45,
    	        'defence' => 55,
	            'sp_attack' => 45, 
            	'sp_defence' => 70,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 87,
        	    'name' => 'Dewgong',
    	        'type1' => 'Water',
	            'type2' => 'Ice',
            	'HP' => 90,
        	    'attack' => 70,
    	        'defence' => 80,
	            'sp_attack' => 70, 
            	'sp_defence' => 95,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 88,
        	    'name' => 'Grimer',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 80,
        	    'attack' => 80,
    	        'defence' => 50,
	            'sp_attack' => 40, 
            	'sp_defence' => 50,
        	    'speed' => 25,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 89,
        	    'name' => 'Muk',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 105,
        	    'attack' => 105,
    	        'defence' => 75,
	            'sp_attack' => 65, 
            	'sp_defence' => 100,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 90,
        	    'name' => 'Shellder',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 30,
        	    'attack' => 65,
    	        'defence' => 100,
	            'sp_attack' => 45, 
            	'sp_defence' => 25,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 91,
        	    'name' => 'Cloyster',
    	        'type1' => 'Water',
	            'type2' => 'Ice',
            	'HP' => 50,
        	    'attack' => 95,
    	        'defence' => 180,
	            'sp_attack' => 85, 
            	'sp_defence' => 45,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 92,
        	    'name' => 'Gastly',
    	        'type1' => 'Ghost',
	            'type2' => 'Poison',
            	'HP' => 30,
        	    'attack' => 35,
    	        'defence' => 30,
	            'sp_attack' => 100, 
            	'sp_defence' => 35,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 93,
        	    'name' => 'Haunter',
    	        'type1' => 'Ghost',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 50,
    	        'defence' => 45,
	            'sp_attack' => 115, 
            	'sp_defence' => 55,
        	    'speed' => 95,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 94,
        	    'name' => 'Gengar',
    	        'type1' => 'Ghost',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 65,
    	        'defence' => 60,
	            'sp_attack' => 130, 
            	'sp_defence' => 75,
        	    'speed' => 110,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 95,
        	    'name' => 'Onix',
    	        'type1' => 'Rock',
	            'type2' => 'Ground',
            	'HP' => 35,
        	    'attack' => 45,
    	        'defence' => 160,
	            'sp_attack' => 30, 
            	'sp_defence' => 45,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 96,
        	    'name' => 'Drowzee',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 60,
        	    'attack' => 48,
    	        'defence' => 45,
	            'sp_attack' => 43, 
            	'sp_defence' => 90,
        	    'speed' => 42,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
        		'id' => 97,
        	    'name' => 'Hypno',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 85,
        	    'attack' => 73,
    	        'defence' => 70,
	            'sp_attack' => 73, 
            	'sp_defence' => 115,
        	    'speed' => 67,
    	        'generation' => 1,
	            'legendary' => 0,
        	],
        	[
				'id' => 98,
				'name' => 'Krabby',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 30,
				'attack' => 105,
				'defence' => 90,
				'sp_attack' => 25, 
				'sp_defence' => 25,
				'speed' => 50,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 99,
				'name' => 'Kingler',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 55,
				'attack' => 130,
				'defence' => 115,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 75,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 100,
				'name' => 'Voltorb',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 40,
				'attack' => 30,
				'defence' => 50,
				'sp_attack' => 55, 
				'sp_defence' => 55,
				'speed' => 100,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 101,
				'name' => 'Electrode',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 60,
				'attack' => 50,
				'defence' => 70,
				'sp_attack' => 80, 
				'sp_defence' => 80,
				'speed' => 140,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 102,
				'name' => 'Exeggcute',
				'type1' => 'Grass',
				'type2' => 'Psychic',
				'HP' => 60,
				'attack' => 40,
				'defence' => 80,
				'sp_attack' => 60, 
				'sp_defence' => 45,
				'speed' => 40,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 103,
				'name' => 'Exeggutor',
				'type1' => 'Grass',
				'type2' => 'Psychic',
				'HP' => 95,
				'attack' => 95,
				'defence' => 85,
				'sp_attack' => 125, 
				'sp_defence' => 65,
				'speed' => 55,
				'generation' => 1,
				'legendary' => 0,
        	],
        	[
				'id' => 104,
				'name' => 'Cubone',
				'type1' => 'Ground',
				'type2' => '',
				'HP' => 50,
				'attack' => 50,
				'defence' => 95,
				'sp_attack' => 40, 
				'sp_defence' => 50,
				'speed' => 35,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 105,
				'name' => 'Marowak',
				'type1' => 'Ground',
				'type2' => '',
				'HP' => 60,
				'attack' => 80,
				'defence' => 110,
				'sp_attack' => 50, 
				'sp_defence' => 80,
				'speed' => 45,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 106,
				'name' => 'Hitmonlee',
				'type1' => 'Fighting',
				'type2' => '',
				'HP' => 50,
				'attack' => 120,
				'defence' => 53,
				'sp_attack' => 35, 
				'sp_defence' => 110,
				'speed' => 87,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 107,
				'name' => 'Hitmonchan',
				'type1' => 'Fighting',
				'type2' => '',
				'HP' => 50,
				'attack' => 105,
				'defence' => 79,
				'sp_attack' => 35, 
				'sp_defence' => 110,
				'speed' => 76,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 108,
				'name' => 'Lickitung',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 90,
				'attack' => 55,
				'defence' => 75,
				'sp_attack' => 60, 
				'sp_defence' => 75,
				'speed' => 30,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 109,
				'name' => 'Koffing',
				'type1' => 'Poison',
				'type2' => '',
				'HP' => 40,
				'attack' => 65,
				'defence' => 95,
				'sp_attack' => 60, 
				'sp_defence' => 45,
				'speed' => 35,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 110,
				'name' => 'Weezing',
				'type1' => 'Poison',
				'type2' => '',
				'HP' => 65,
				'attack' => 90,
				'defence' => 120,
				'sp_attack' => 85, 
				'sp_defence' => 70,
				'speed' => 60,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 111,
				'name' => 'Rhyhorn',
				'type1' => 'Ground',
				'type2' => 'Rock',
				'HP' => 80,
				'attack' => 85,
				'defence' => 95,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 25,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 112,
				'name' => 'Rhydon',
				'type1' => 'Ground',
				'type2' => 'Rock',
				'HP' => 105,
				'attack' => 130,
				'defence' => 120,
				'sp_attack' => 45, 
				'sp_defence' => 45,
				'speed' => 40,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 113,
				'name' => 'Chansey',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 250,
				'attack' => 5,
				'defence' => 5,
				'sp_attack' => 35, 
				'sp_defence' => 105,
				'speed' => 50,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 114,
				'name' => 'Tangela',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 65,
				'attack' => 55,
				'defence' => 115,
				'sp_attack' => 100, 
				'sp_defence' => 40,
				'speed' => 60,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 115,
				'name' => 'Kangaskhan',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 105,
				'attack' => 95,
				'defence' => 80,
				'sp_attack' => 40, 
				'sp_defence' => 80,
				'speed' => 90,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 116,
				'name' => 'Horsea',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 30,
				'attack' => 40,
				'defence' => 70,
				'sp_attack' => 70, 
				'sp_defence' => 25,
				'speed' => 60,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 117,
				'name' => 'Seadra',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 55,
				'attack' => 65,
				'defence' => 95,
				'sp_attack' => 95, 
				'sp_defence' => 45,
				'speed' => 85,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 118,
				'name' => 'Goldeen',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 45,
				'attack' => 67,
				'defence' => 60,
				'sp_attack' => 35, 
				'sp_defence' => 50,
				'speed' => 63,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 119,
				'name' => 'Seaking',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 80,
				'attack' => 92,
				'defence' => 65,
				'sp_attack' => 65, 
				'sp_defence' => 80,
				'speed' => 68,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 120,
				'name' => 'Staryu',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 30,
				'attack' => 45,
				'defence' => 55,
				'sp_attack' => 70, 
				'sp_defence' => 55,
				'speed' => 85,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 121,
				'name' => 'Starmie',
				'type1' => 'Water',
				'type2' => 'Psychic',
				'HP' => 60,
				'attack' => 75,
				'defence' => 85,
				'sp_attack' => 100, 
				'sp_defence' => 85,
				'speed' => 115,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 122,
				'name' => 'Mr. Mime',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 40,
				'attack' => 45,
				'defence' => 65,
				'sp_attack' => 100, 
				'sp_defence' => 120,
				'speed' => 90,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 123,
				'name' => 'Scyther',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 70,
				'attack' => 110,
				'defence' => 80,
				'sp_attack' => 55, 
				'sp_defence' => 80,
				'speed' => 105,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 124,
				'name' => 'Jynx',
				'type1' => 'Ice',
				'type2' => 'Psychic',
				'HP' => 65,
				'attack' => 50,
				'defence' => 35,
				'sp_attack' => 115, 
				'sp_defence' => 95,
				'speed' => 95,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 125,
				'name' => 'Electabuzz',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 65,
				'attack' => 83,
				'defence' => 57,
				'sp_attack' => 95, 
				'sp_defence' => 85,
				'speed' => 105,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 126,
				'name' => 'Magmar',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 65,
				'attack' => 95,
				'defence' => 57,
				'sp_attack' => 100, 
				'sp_defence' => 85,
				'speed' => 93,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 127,
				'name' => 'Pinsir',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 65,
				'attack' => 125,
				'defence' => 100,
				'sp_attack' => 55, 
				'sp_defence' => 70,
				'speed' => 85,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 128,
				'name' => 'Tauros',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 75,
				'attack' => 100,
				'defence' => 95,
				'sp_attack' => 40, 
				'sp_defence' => 70,
				'speed' => 110,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 129,
				'name' => 'Magikarp',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 20,
				'attack' => 10,
				'defence' => 55,
				'sp_attack' => 15, 
				'sp_defence' => 20,
				'speed' => 80,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 130,
				'name' => 'Gyarados',
				'type1' => 'Water',
				'type2' => 'Flying',
				'HP' => 95,
				'attack' => 125,
				'defence' => 79,
				'sp_attack' => 60, 
				'sp_defence' => 100,
				'speed' => 81,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 131,
				'name' => 'Lapras',
				'type1' => 'Water',
				'type2' => 'Ice',
				'HP' => 130,
				'attack' => 85,
				'defence' => 80,
				'sp_attack' => 85, 
				'sp_defence' => 95,
				'speed' => 60,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 132,
				'name' => 'Ditto',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 48,
				'attack' => 48,
				'defence' => 48,
				'sp_attack' => 58, 
				'sp_defence' => 48,
				'speed' => 48,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 133,
				'name' => 'Eevee',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 55,
				'attack' => 55,
				'defence' => 50,
				'sp_attack' => 45, 
				'sp_defence' => 65,
				'speed' => 55,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 134,
				'name' => 'Vaporeon',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 130,
				'attack' => 65,
				'defence' => 60,
				'sp_attack' => 110, 
				'sp_defence' => 95,
				'speed' => 65,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 135,
				'name' => 'Jolteon',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 65,
				'attack' => 65,
				'defence' => 60,
				'sp_attack' => 110, 
				'sp_defence' => 95,
				'speed' => 130,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 136,
				'name' => 'Flareon',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 65,
				'attack' => 130,
				'defence' => 60,
				'sp_attack' => 95, 
				'sp_defence' => 110,
				'speed' => 65,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 137,
				'name' => 'Porygon',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 65,
				'attack' => 60,
				'defence' => 70,
				'sp_attack' => 85, 
				'sp_defence' => 75,
				'speed' => 40,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 138,
				'name' => 'Omanyte',
				'type1' => 'Rock',
				'type2' => 'Water',
				'HP' => 35,
				'attack' => 40,
				'defence' => 100,
				'sp_attack' => 90, 
				'sp_defence' => 55,
				'speed' => 35,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 139,
				'name' => 'Omastar',
				'type1' => 'Rock',
				'type2' => 'Water',
				'HP' => 70,
				'attack' => 60,
				'defence' => 125,
				'sp_attack' => 115, 
				'sp_defence' => 70,
				'speed' => 55,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 140,
				'name' => 'Kabuto',
				'type1' => 'Rock',
				'type2' => 'Water',
				'HP' => 30,
				'attack' => 80,
				'defence' => 90,
				'sp_attack' => 55, 
				'sp_defence' => 45,
				'speed' => 55,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 141,
				'name' => 'Kabutops',
				'type1' => 'Rock',
				'type2' => 'Water',
				'HP' => 60,
				'attack' => 115,
				'defence' => 105,
				'sp_attack' => 65, 
				'sp_defence' => 70,
				'speed' => 80,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 142,
				'name' => 'Aerodactyl',
				'type1' => 'Rock',
				'type2' => 'Flying',
				'HP' => 80,
				'attack' => 105,
				'defence' => 65,
				'sp_attack' => 60, 
				'sp_defence' => 75,
				'speed' => 130,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 143,
				'name' => 'Snorlax',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 160,
				'attack' => 110,
				'defence' => 65,
				'sp_attack' => 65, 
				'sp_defence' => 110,
				'speed' => 30,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 144,
				'name' => 'Articuno',
				'type1' => 'Ice',
				'type2' => 'Flying',
				'HP' => 90,
				'attack' => 85,
				'defence' => 100,
				'sp_attack' => 95, 
				'sp_defence' => 125,
				'speed' => 85,
				'generation' => 1,
				'legendary' => 1,
        	],
			[
				'id' => 145,
				'name' => 'Zapdos',
				'type1' => 'Electric',
				'type2' => 'Flying',
				'HP' => 90,
				'attack' => 90,
				'defence' => 85,
				'sp_attack' => 125, 
				'sp_defence' => 90,
				'speed' => 100,
				'generation' => 1,
				'legendary' => 1,
        	],
			[
				'id' => 146,
				'name' => 'Moltres',
				'type1' => 'Fire',
				'type2' => 'Flying',
				'HP' => 90,
				'attack' => 100,
				'defence' => 90,
				'sp_attack' => 125, 
				'sp_defence' => 85,
				'speed' => 90,
				'generation' => 1,
				'legendary' => 1,
        	],
			[
				'id' => 147,
				'name' => 'Dratini',
				'type1' => 'Dragon',
				'type2' => '',
				'HP' => 41,
				'attack' => 64,
				'defence' => 45,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 50,
				'generation' => 1,
				'legendary' => 0,
        	],
			[
				'id' => 148,
				'name' => 'Dragonair',
				'type1' => 'Dragon',
				'type2' => '',
				'HP' => 61,
				'attack' => 84,
				'defence' => 65,
				'sp_attack' => 70, 
				'sp_defence' => 70,
				'speed' => 70,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 149,
				'name' => 'Dragonite',
				'type1' => 'Dragon',
				'type2' => 'Flying',
				'HP' => 91,
				'attack' => 134,
				'defence' => 95,
				'sp_attack' => 100, 
				'sp_defence' => 100,
				'speed' => 80,
				'generation' => 1,
				'legendary' => 0,
			],
			[
				'id' => 150,
				'name' => 'Mewtwo',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 106,
				'attack' => 110,
				'defence' => 90,
				'sp_attack' => 154, 
				'sp_defence' => 90,
				'speed' => 130,
				'generation' => 1,
				'legendary' => 1,
			],
			[
				'id' => 151,
				'name' => 'Mew',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 100,
				'attack' => 100,
				'defence' => 100,
				'sp_attack' => 100, 
				'sp_defence' => 100,
				'speed' => 100,
				'generation' => 1,
				'legendary' => 1,
			]
		]);
	}
}
