<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PokedexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pokedex')->insert(
        	[
        		'id' => 1,
        	    'name' => 'Bulbasaur',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 49,
    	        'defence' => 49,
	            'sp_attack' => 65, 
            	'sp_defence' => 65,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 2,
        	    'name' => 'Ivysaur',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 62,
    	        'defence' => 63,
	            'sp_attack' => 80, 
            	'sp_defence' => 80,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 3,
        	    'name' => 'Venusaur',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 80,
        	    'attack' => 82,
    	        'defence' => 83,
	            'sp_attack' => 100, 
            	'sp_defence' => 100,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 4,
        	    'name' => 'Charmander',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 39,
        	    'attack' => 52,
    	        'defence' => 43,
	            'sp_attack' => 60, 
            	'sp_defence' => 50,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 5,
        	    'name' => 'Charmeleon',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 58,
        	    'attack' => 64,
    	        'defence' => 58,
	            'sp_attack' => 80, 
            	'sp_defence' => 65,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 6,
        	    'name' => 'Charizard',
    	        'type1' => 'Fire',
	            'type2' => 'Flying',
            	'HP' => 78,
        	    'attack' => 84,
    	        'defence' => 78,
	            'sp_attack' => 109, 
            	'sp_defence' => 85,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 7,
        	    'name' => 'Squirtle',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 44,
        	    'attack' => 48,
    	        'defence' => 65,
	            'sp_attack' => 50, 
            	'sp_defence' => 64,
        	    'speed' => 43,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 8,
        	    'name' => 'Wartortle',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 59,
        	    'attack' => 63,
    	        'defence' => 80,
	            'sp_attack' => 65, 
            	'sp_defence' => 80,
        	    'speed' => 58,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 9,
        	    'name' => 'Blastoise',
    	        'type1' => 'Water',
	            'type2' => '',
            	'HP' => 79,
        	    'attack' => 83,
    	        'defence' => 100,
	            'sp_attack' => 85, 
            	'sp_defence' => 105,
        	    'speed' => 78,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 10,
        	    'name' => 'Caterpie',
    	        'type1' => 'Bug',
	            'type2' => '',
            	'HP' => 45,
        	    'attack' => 30,
    	        'defence' => 35,
	            'sp_attack' => 20, 
            	'sp_defence' => 20,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 11,
        	    'name' => 'Metapod',
    	        'type1' => 'Bug',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 20,
    	        'defence' => 55,
	            'sp_attack' => 25, 
            	'sp_defence' => 25,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 12,
        	    'name' => 'Butterfree',
    	        'type1' => 'Bug',
	            'type2' => 'Flying',
            	'HP' => 60,
        	    'attack' => 45,
    	        'defence' => 50,
	            'sp_attack' => 90, 
            	'sp_defence' => 80,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 13,
        	    'name' => 'Weedle',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 40,
        	    'attack' => 35,
    	        'defence' => 30,
	            'sp_attack' => 20, 
            	'sp_defence' => 20,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 14,
        	    'name' => 'Kakuna',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 25,
    	        'defence' => 50,
	            'sp_attack' => 25, 
            	'sp_defence' => 25,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 15,
        	    'name' => 'Beedrill',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 65,
        	    'attack' => 90,
    	        'defence' => 40,
	            'sp_attack' => 45, 
            	'sp_defence' => 80,
        	    'speed' => 75,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 16,
        	    'name' => 'Pidgey',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 45,
    	        'defence' => 40,
	            'sp_attack' => 35, 
            	'sp_defence' => 35,
        	    'speed' => 56,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 17,
        	    'name' => 'Pidgeotto',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 63,
        	    'attack' => 60,
    	        'defence' => 55,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 71,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 18,
        	    'name' => 'Pidgeot',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 83,
        	    'attack' => 80,
    	        'defence' => 75,
	            'sp_attack' => 70, 
            	'sp_defence' => 70,
        	    'speed' => 101,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 19,
        	    'name' => 'Rattata',
    	        'type1' => 'Normal',
	            'type2' => '',
            	'HP' => 30,
        	    'attack' => 56,
    	        'defence' => 35,
	            'sp_attack' => 25, 
            	'sp_defence' => 35,
        	    'speed' => 72,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 20,
        	    'name' => 'Raticate',
    	        'type1' => 'Normal',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 81,
    	        'defence' => 60,
	            'sp_attack' => 50, 
            	'sp_defence' => 70,
        	    'speed' => 97,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 21,
        	    'name' => 'Spearow',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 60,
    	        'defence' => 30,
	            'sp_attack' => 31, 
            	'sp_defence' => 31,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 22,
        	    'name' => 'Fearow',
    	        'type1' => 'Normal',
	            'type2' => 'Flying',
            	'HP' => 65,
        	    'attack' => 90,
    	        'defence' => 65,
	            'sp_attack' => 61, 
            	'sp_defence' => 61,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 23,
        	    'name' => 'Ekans',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 35,
        	    'attack' => 60,
    	        'defence' => 44,
	            'sp_attack' => 40, 
            	'sp_defence' => 54,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 24,
        	    'name' => 'Arbok',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 60,
        	    'attack' => 85,
    	        'defence' => 69,
	            'sp_attack' => 65, 
            	'sp_defence' => 79,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 25,
        	    'name' => 'Pikachu',
    	        'type1' => 'Electric',
	            'type2' => '',
            	'HP' => 35,
        	    'attack' => 55,
    	        'defence' => 40,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 26,
        	    'name' => 'Raichu',
    	        'type1' => 'Electric',
	            'type2' => '',
            	'HP' => 60,
        	    'attack' => 90,
    	        'defence' => 55,
	            'sp_attack' => 90, 
            	'sp_defence' => 80,
        	    'speed' => 110,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 27,
        	    'name' => 'Sandshrew',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 50,
        	    'attack' => 75,
    	        'defence' => 85,
	            'sp_attack' => 20, 
            	'sp_defence' => 30,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 28,
        	    'name' => 'Sandslash',
    	        'type1' => 'Ground',
	            'type2' => '',
            	'HP' => 75,
        	    'attack' => 100,
    	        'defence' => 110,
	            'sp_attack' => 45, 
            	'sp_defence' => 55,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 29,
        	    'name' => 'Nidoran(Female)',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 55,
        	    'attack' => 47,
    	        'defence' => 52,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 41,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 30,
        	    'name' => 'Nidorina',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 70,
        	    'attack' => 62,
    	        'defence' => 67,
	            'sp_attack' => 55, 
            	'sp_defence' => 55,
        	    'speed' => 56,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 31,
        	    'name' => 'Nidoqueen',
    	        'type1' => 'Poison',
	            'type2' => 'Ground',
            	'HP' => 90,
        	    'attack' => 92,
    	        'defence' => 87,
	            'sp_attack' => 75, 
            	'sp_defence' => 85,
        	    'speed' => 76,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 32,
        	    'name' => 'Nidoran(Male)',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 46,
        	    'attack' => 57,
    	        'defence' => 40,
	            'sp_attack' => 40, 
            	'sp_defence' => 40,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 33,
        	    'name' => 'Nidorino',
    	        'type1' => 'Poison',
	            'type2' => '',
            	'HP' => 61,
        	    'attack' => 72,
    	        'defence' => 57,
	            'sp_attack' => 55, 
            	'sp_defence' => 55,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 34,
        	    'name' => 'Nidoking',
    	        'type1' => 'Poison',
	            'type2' => 'Ground',
            	'HP' => 81,
        	    'attack' => 102,
    	        'defence' => 77,
	            'sp_attack' => 85, 
            	'sp_defence' => 75,
        	    'speed' => 85,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 35,
        	    'name' => 'Clefairy',
    	        'type1' => 'Fairy',
	            'type2' => '',
            	'HP' => 70,
        	    'attack' => 45,
    	        'defence' => 48,
	            'sp_attack' => 60, 
            	'sp_defence' => 65,
        	    'speed' => 35,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 36,
        	    'name' => 'Clefable',
    	        'type1' => 'Fairy',
	            'type2' => '',
            	'HP' => 95,
        	    'attack' => 70,
    	        'defence' => 73,
	            'sp_attack' => 95, 
            	'sp_defence' => 90,
        	    'speed' => 60,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 37,
        	    'name' => 'Vulpix',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 38,
        	    'attack' => 41,
    	        'defence' => 40,
	            'sp_attack' => 50, 
            	'sp_defence' => 65,
        	    'speed' => 65,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 38,
        	    'name' => 'Ninetales',
    	        'type1' => 'Fire',
	            'type2' => '',
            	'HP' => 73,
        	    'attack' => 76,
    	        'defence' => 75,
	            'sp_attack' => 81, 
            	'sp_defence' => 100,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 39,
        	    'name' => 'Jigglypuff',
    	        'type1' => 'Normal',
	            'type2' => 'Fairy',
            	'HP' => 115,
        	    'attack' => 45,
    	        'defence' => 20,
	            'sp_attack' => 45, 
            	'sp_defence' => 25,
        	    'speed' => 20,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 40,
        	    'name' => 'Wigglytuff',
    	        'type1' => 'Normal',
	            'type2' => 'Fairy',
            	'HP' => 140,
        	    'attack' => 70,
    	        'defence' => 45,
	            'sp_attack' => 85, 
            	'sp_defence' => 50,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 41,
        	    'name' => 'Zubat',
    	        'type1' => 'Poison',
	            'type2' => 'Flying',
            	'HP' => 40,
        	    'attack' => 45,
    	        'defence' => 35,
	            'sp_attack' => 30, 
            	'sp_defence' => 40,
        	    'speed' => 55,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 42,
        	    'name' => 'Golbat',
    	        'type1' => 'Poison',
	            'type2' => 'Flying',
            	'HP' => 75,
        	    'attack' => 80,
    	        'defence' => 70,
	            'sp_attack' => 65, 
            	'sp_defence' => 75,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 43,
        	    'name' => 'Oddish',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 45,
        	    'attack' => 50,
    	        'defence' => 55,
	            'sp_attack' => 75, 
            	'sp_defence' => 65,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 44,
        	    'name' => 'Gloom',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 65,
    	        'defence' => 70,
	            'sp_attack' => 85, 
            	'sp_defence' => 75,
        	    'speed' => 40,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 45,
        	    'name' => 'Vileplume',
    	        'type1' => 'Grass',
	            'type2' => 'Poison',
            	'HP' => 75,
        	    'attack' => 80,
    	        'defence' => 85,
	            'sp_attack' => 110, 
            	'sp_defence' => 90,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 46,
        	    'name' => 'Paras',
    	        'type1' => 'Bug',
	            'type2' => 'Grass',
            	'HP' => 35,
        	    'attack' => 70,
    	        'defence' => 55,
	            'sp_attack' => 45, 
            	'sp_defence' => 55,
        	    'speed' => 25,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 47,
        	    'name' => 'Parasect',
    	        'type1' => 'Bug',
	            'type2' => 'Grass',
            	'HP' => 60,
        	    'attack' => 95,
    	        'defence' => 80,
	            'sp_attack' => 60, 
            	'sp_defence' => 80,
        	    'speed' => 30,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 48,
        	    'name' => 'Venonat',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 60,
        	    'attack' => 55,
    	        'defence' => 50,
	            'sp_attack' => 40, 
            	'sp_defence' => 55,
        	    'speed' => 45,
    	        'generation' => 1,
	            'legendary' => 0
        	],
        	[
        		'id' => 49,
        	    'name' => 'Venomoth',
    	        'type1' => 'Bug',
	            'type2' => 'Poison',
            	'HP' => 70,
        	    'attack' => 65,
    	        'defence' => 60,
	            'sp_attack' => 90, 
            	'sp_defence' => 75,
        	    'speed' => 90,
    	        'generation' => 1,
	            'legendary' => 0
        	],





(50, 'Diglett', 'Ground', '', 10, 55, 25, 35, 45, 95, 1, 0),
(51, 'Dugtrio', 'Ground', '', 35, 80, 50, 50, 70, 120, 1, 0),
(52, 'Meowth', 'Normal', '', 40, 45, 35, 40, 40, 90, 1, 0),
(53, 'Persian', 'Normal', '', 65, 70, 60, 65, 65, 115, 1, 0),
(54, 'Psyduck', 'Water', '', 50, 52, 48, 65, 50, 55, 1, 0),
(55, 'Golduck', 'Water', '', 80, 82, 78, 95, 80, 85, 1, 0),
(56, 'Mankey', 'Fighting', '', 40, 80, 35, 35, 45, 70, 1, 0),
(57, 'Primeape', 'Fighting', '', 65, 105, 60, 60, 70, 95, 1, 0),
(58, 'Growlithe', 'Fire', '', 55, 70, 45, 70, 50, 60, 1, 0),
(59, 'Arcanine', 'Fire', '', 90, 110, 80, 100, 80, 95, 1, 0),
(60, 'Poliwag', 'Water', '', 40, 50, 40, 40, 40, 90, 1, 0),
(61, 'Poliwhirl', 'Water', '', 65, 65, 65, 50, 50, 90, 1, 0),
(62, 'Poliwrath', 'Water', 'Fighting', 90, 95, 95, 70, 90, 70, 1, 0),
(63, 'Abra', 'Psychic', '', 25, 20, 15, 105, 55, 90, 1, 0),
(64, 'Kadabra', 'Psychic', '', 40, 35, 30, 120, 70, 105, 1, 0),
(65, 'Alakazam', 'Psychic', '', 55, 50, 45, 135, 95, 120, 1, 0),
(66, 'Machop', 'Fighting', '', 70, 80, 50, 35, 35, 35, 1, 0),
(67, 'Machoke', 'Fighting', '', 80, 100, 70, 50, 60, 45, 1, 0),
(68, 'Machamp', 'Fighting', '', 90, 130, 80, 65, 85, 55, 1, 0),
(69, 'Bellsprout', 'Grass', 'Poison', 50, 75, 35, 70, 30, 40, 1, 0),
(70, 'Weepinbell', 'Grass', 'Poison', 65, 90, 50, 85, 45, 55, 1, 0),
(71, 'Victreebel', 'Grass', 'Poison', 80, 105, 65, 100, 70, 70, 1, 0),
(72, 'Tentacool', 'Water', 'Poison', 40, 40, 35, 50, 100, 70, 1, 0),
(73, 'Tentacruel', 'Water', 'Poison', 80, 70, 65, 80, 120, 100, 1, 0),
(74, 'Geodude', 'Rock', 'Ground', 40, 80, 100, 30, 30, 20, 1, 0),
(75, 'Graveler', 'Rock', 'Ground', 55, 95, 115, 45, 45, 35, 1, 0),
(76, 'Golem', 'Rock', 'Ground', 80, 120, 130, 55, 65, 45, 1, 0),
(77, 'Ponyta', 'Fire', '', 50, 85, 55, 65, 65, 90, 1, 0),
(78, 'Rapidash', 'Fire', '', 65, 100, 70, 80, 80, 105, 1, 0),
(79, 'Slowpoke', 'Water', 'Psychic', 90, 65, 65, 40, 40, 15, 1, 0),
(80, 'Slowbro', 'Water', 'Psychic', 95, 75, 110, 100, 80, 30, 1, 0),
(81, 'Magnemite', 'Electric', 'Steel', 25, 35, 70, 95, 55, 45, 1, 0),
(82, 'Magneton', 'Electric', 'Steel', 50, 60, 95, 120, 70, 70, 1, 0),
(83, 'Farfetch\'d', 'Normal', 'Flying', 52, 65, 55, 58, 62, 60, 1, 0),
(84, 'Doduo', 'Normal', 'Flying', 35, 85, 45, 35, 35, 75, 1, 0),
(85, 'Dodrio', 'Normal', 'Flying', 60, 110, 70, 60, 60, 100, 1, 0),
(86, 'Seel', 'Water', '', 65, 45, 55, 45, 70, 45, 1, 0),
(87, 'Dewgong', 'Water', 'Ice', 90, 70, 80, 70, 95, 70, 1, 0),
(88, 'Grimer', 'Poison', '', 80, 80, 50, 40, 50, 25, 1, 0),
(89, 'Muk', 'Poison', '', 105, 105, 75, 65, 100, 50, 1, 0),
(90, 'Shellder', 'Water', '', 30, 65, 100, 45, 25, 40, 1, 0),
(91, 'Cloyster', 'Water', 'Ice', 50, 95, 180, 85, 45, 70, 1, 0),
(92, 'Gastly', 'Ghost', 'Poison', 30, 35, 30, 100, 35, 80, 1, 0),
(93, 'Haunter', 'Ghost', 'Poison', 45, 50, 45, 115, 55, 95, 1, 0),
(94, 'Gengar', 'Ghost', 'Poison', 60, 65, 60, 130, 75, 110, 1, 0),
(95, 'Onix', 'Rock', 'Ground', 35, 45, 160, 30, 45, 70, 1, 0),
(96, 'Drowzee', 'Psychic', '', 60, 48, 45, 43, 90, 42, 1, 0),
(97, 'Hypno', 'Psychic', '', 85, 73, 70, 73, 115, 67, 1, 0),
(98, 'Krabby', 'Water', '', 30, 105, 90, 25, 25, 50, 1, 0),
(99, 'Kingler', 'Water', '', 55, 130, 115, 50, 50, 75, 1, 0),
(100, 'Voltorb', 'Electric', '', 40, 30, 50, 55, 55, 100, 1, 0),
(101, 'Electrode', 'Electric', '', 60, 50, 70, 80, 80, 140, 1, 0),
(102, 'Exeggcute', 'Grass', 'Psychic', 60, 40, 80, 60, 45, 40, 1, 0),
(103, 'Exeggutor', 'Grass', 'Psychic', 95, 95, 85, 125, 65, 55, 1, 0),
(104, 'Cubone', 'Ground', '', 50, 50, 95, 40, 50, 35, 1, 0),
(105, 'Marowak', 'Ground', '', 60, 80, 110, 50, 80, 45, 1, 0),
(106, 'Hitmonlee', 'Fighting', '', 50, 120, 53, 35, 110, 87, 1, 0),
(107, 'Hitmonchan', 'Fighting', '', 50, 105, 79, 35, 110, 76, 1, 0),
(108, 'Lickitung', 'Normal', '', 90, 55, 75, 60, 75, 30, 1, 0),
(109, 'Koffing', 'Poison', '', 40, 65, 95, 60, 45, 35, 1, 0),
(110, 'Weezing', 'Poison', '', 65, 90, 120, 85, 70, 60, 1, 0),
(111, 'Rhyhorn', 'Ground', 'Rock', 80, 85, 95, 30, 30, 25, 1, 0),
(112, 'Rhydon', 'Ground', 'Rock', 105, 130, 120, 45, 45, 40, 1, 0),
(113, 'Chansey', 'Normal', '', 250, 5, 5, 35, 105, 50, 1, 0),
(114, 'Tangela', 'Grass', '', 65, 55, 115, 100, 40, 60, 1, 0),
(115, 'Kangaskhan', 'Normal', '', 105, 95, 80, 40, 80, 90, 1, 0),
(116, 'Horsea', 'Water', '', 30, 40, 70, 70, 25, 60, 1, 0),
(117, 'Seadra', 'Water', '', 55, 65, 95, 95, 45, 85, 1, 0),
(118, 'Goldeen', 'Water', '', 45, 67, 60, 35, 50, 63, 1, 0),
(119, 'Seaking', 'Water', '', 80, 92, 65, 65, 80, 68, 1, 0),
(120, 'Staryu', 'Water', '', 30, 45, 55, 70, 55, 85, 1, 0),
(121, 'Starmie', 'Water', 'Psychic', 60, 75, 85, 100, 85, 115, 1, 0),
(122, 'Mr. Mime', 'Psychic', 'Fairy', 40, 45, 65, 100, 120, 90, 1, 0),
(123, 'Scyther', 'Bug', 'Flying', 70, 110, 80, 55, 80, 105, 1, 0),
(124, 'Jynx', 'Ice', 'Psychic', 65, 50, 35, 115, 95, 95, 1, 0),
(125, 'Electabuzz', 'Electric', '', 65, 83, 57, 95, 85, 105, 1, 0),
(126, 'Magmar', 'Fire', '', 65, 95, 57, 100, 85, 93, 1, 0),
(127, 'Pinsir', 'Bug', '', 65, 125, 100, 55, 70, 85, 1, 0),
(128, 'Tauros', 'Normal', '', 75, 100, 95, 40, 70, 110, 1, 0),
(129, 'Magikarp', 'Water', '', 20, 10, 55, 15, 20, 80, 1, 0),
(130, 'Gyarados', 'Water', 'Flying', 95, 125, 79, 60, 100, 81, 1, 0),
(131, 'Lapras', 'Water', 'Ice', 130, 85, 80, 85, 95, 60, 1, 0),
(132, 'Ditto', 'Normal', '', 48, 48, 48, 48, 48, 48, 1, 0),
(133, 'Eevee', 'Normal', '', 55, 55, 50, 45, 65, 55, 1, 0),
(134, 'Vaporeon', 'Water', '', 130, 65, 60, 110, 95, 65, 1, 0),
(135, 'Jolteon', 'Electric', '', 65, 65, 60, 110, 95, 130, 1, 0),
(136, 'Flareon', 'Fire', '', 65, 130, 60, 95, 110, 65, 1, 0),
(137, 'Porygon', 'Normal', '', 65, 60, 70, 85, 75, 40, 1, 0),
(138, 'Omanyte', 'Rock', 'Water', 35, 40, 100, 90, 55, 35, 1, 0),
(139, 'Omastar', 'Rock', 'Water', 70, 60, 125, 115, 70, 55, 1, 0),
(140, 'Kabuto', 'Rock', 'Water', 30, 80, 90, 55, 45, 55, 1, 0),
(141, 'Kabutops', 'Rock', 'Water', 60, 115, 105, 65, 70, 80, 1, 0),
(142, 'Aerodactyl', 'Rock', 'Flying', 80, 105, 65, 60, 75, 130, 1, 0),
(143, 'Snorlax', 'Normal', '', 160, 110, 65, 65, 110, 30, 1, 0),
(144, 'Articuno', 'Ice', 'Flying', 90, 85, 100, 95, 125, 85, 1, 0),
(145, 'Zapdos', 'Electric', 'Flying', 90, 90, 85, 125, 90, 100, 1, 0),
(146, 'Moltres', 'Fire', 'Flying', 90, 100, 90, 125, 85, 90, 1, 0),

			[
        		'id' => 147,
        	    'name' => 'Dratini',
    	        'type1' => 'Dragon',
	            'type2' => '',
            	'HP' => 41,
        	    'attack' => 64,
    	        'defence' => 45,
	            'sp_attack' => 50, 
            	'sp_defence' => 50,
        	    'speed' => 50,
    	        'generation' => 1,
	            'legendary' => 0
        	],
			[
        		'id' => 148,
        	    'name' => 'Dragonair',
    	        'type1' => 'Dragon',
	            'type2' => '',
            	'HP' => 61,
        	    'attack' => 84,
    	        'defence' => 65,
	            'sp_attack' => 70, 
            	'sp_defence' => 70,
        	    'speed' => 70,
    	        'generation' => 1,
	            'legendary' => 0
        	],
			[
        		'id' => 149,
        	    'name' => 'Dragonite',
    	        'type1' => 'Dragon',
	            'type2' => 'Flying',
            	'HP' => 91,
        	    'attack' => 134,
    	        'defence' => 95,
	            'sp_attack' => 100, 
            	'sp_defence' => 100,
        	    'speed' => 80,
    	        'generation' => 1,
	            'legendary' => 0
        	],
			[
        		'id' => 150,
        	    'name' => 'Mewtwo',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 106,
        	    'attack' => 110,
    	        'defence' => 90,
	            'sp_attack' => 154, 
            	'sp_defence' => 90,
        	    'speed' => 130,
    	        'generation' => 1,
	            'legendary' => 0
        	],
			[
        		'id' => 151,
        	    'name' => 'Mew',
    	        'type1' => 'Psychic',
	            'type2' => '',
            	'HP' => 100,
        	    'attack' => 100,
    	        'defence' => 100,
	            'sp_attack' => 100, 
            	'sp_defence' => 100,
        	    'speed' => 100,
    	        'generation' => 1,
	            'legendary' => 0
        	]
    	);
    }
}
